# Generated by Django 5.2.6 on 2025-09-23 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_salesorder_salesorderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock_quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Quantidade em Estoque'),
        ),
    ]
